export enum PlugActionTypes {
  IS_CONNECT_PLUG = 'IS_CONNECT_PLUG',
  CONNECT_PLUG = 'CONNECT_PLUG',
  GET_ACCOUNT_ID_PLUG = 'GET_ACCOUNT_ID_PLUG',
  GET_BALANCE_PLUG = 'GET_BALANCE_PLUG',
  INITIAL_STATE_PLUG = 'INITIAL_STATE_PLUG',
  SET_STATE = 'PLUG_SET_STATE',
}
