export enum ActionsMetamask {
  CONNECT_METAMASK = 'CONNECT_METAMASK',
  GET_ADDRESS_METAMASK = 'GET_ADDRESS_METAMASK',
  SEND_TRANSACTION_METAMASK = 'SEND_TRANSACTION_METAMASK',
  SET_ADDRESS_METAMASK = 'SET_ADDRESS_METAMASK',
  IS_CONNECTED_METAMASK = 'IS_CONNECTED_METAMASK',
  INITIAL_STATE_METAMASK = 'INITIAL_STATE_METAMASK',
  GET_ACCOUNT_INFO_METAMASK = 'GET_ACCOUNT_INFO_METAMASK',
}
