export enum ActionsMetamask {
  CONNECT_METAMASK = 'CONNECT_METAMASK',
  GET_ADDRESS = 'GET_ADDRESS',
  SEND_TRANSACTION = 'SEND_TRANSACTION',
  SET_ADDRESS = 'SET_ADDRESS',
  IS_CONNECTED = 'IS_CONNECTED',
  INITIAL_STATE = 'INITITAL_STATE',
}
