export enum ActionsTransaction {
  SENDING = 'SENDING',
  SET_AMOUNT = 'SET_AMOUNT',
  GET_AMOUNT = 'GET_AMOUNT',
  SET_FROM = 'SET_FROM',
  GET_FROM = 'GET_FROM',
  INITIAL_STATE_TRANSACTION = 'INITIAL_STATE_TRANSACTION',
  SET_RECEIVING = 'SET_RECEIVING',
}
