---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_port: 22
    ansible_connection: ssh

project:
  hosts:    
    develop:
      ansible_host: 54.152.148.205
      ansible_user: ubuntu
    # development
