export enum StepsActionType {
  INCREMENT_STEP = 'INCREMENT_STEP',
  DECREMENT_STEP = 'DECREMENT_STEP',
  INITIAL_STEP = 'INITIAL_STEP',
  SET_STATE = 'SET_STATE',
  STEP_TO_START = 'STEP_TO_START',
}
